version: '2'
services:
  flight_app-app:
    image: flight_app
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://flight_app-postgresql:5432/flight_app
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  flight_app-postgresql:
    extends:
      file: postgresql.yml
      service: flight_app-postgresql
