version: '2'
services:
  flight_app-postgresql:
    image: postgres:12.3
    # volumes:
    #     - ~/volumes/jhipster/flight_app/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=flight_app
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5432
